name: Lint and run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  lint-and-run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --all-extras

      - name: Run lint
        run: |
          poetry run flake8 cirro

      - name: Run Tests
        working-directory: tests
        run: |
          poetry run pytest --cov --cov-report=xml --cov-branch -o junit_family=xunit2 --junitxml=junit/test-results.xml
