name: Build Python package

on:
  release:
    types:
      - published
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Test install
        run: |
          poetry install --all-extras
          poetry run cirro

      - name: Build python package
        run: |
          poetry build

      - name: Publish python package
        if: github.event_name == 'release'
        run: |
          poetry publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
